# Generated by Django 3.2.12 on 2022-03-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('cost', models.IntegerField(verbose_name='金額')),
                ('star', models.IntegerField(verbose_name='満足度')),
                ('satiety', models.IntegerField(verbose_name='満腹度')),
                ('category', models.CharField(max_length=50, verbose_name='名前')),
                ('detail', models.TextField(verbose_name='詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
        ),
    ]
