# Generated by Django 3.2.12 on 2022-03-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('家', 'HOME'), ('外食', 'OUT')], default='カテゴリー', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='detail',
            field=models.TextField(blank=True, verbose_name='詳細'),
        ),
    ]
