# Generated by Django 3.2.12 on 2022-03-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220331_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('HOME', '家'), ('OUT', '外食')], default='カテゴリー', max_length=50),
        ),
    ]
